obstacle_range: 2.5
raytrace_range: 2.8

#4'x8' => 1.2192m x 2.4384m 
#         0.6096m     1.2192m
#footprint: [[-0.6096, 1.2192], [0.6096, 1.2192], [0.6096, -1.2192],  [-0.6096, -1.2192]]
footprint: [[1.9384, -0.6096], [1.9384, 0.6096], [-0.5, 0.6096], [-0.5, -0.6096]]

transform_tolerance: 0.5

plugins:
- {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
- {name: static_layer,    type: "costmap_2d::StaticLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  enabled:             True
  map_topic:           /map
  first_map_only:      False
  track_unknown_space: True
  # True:  NO_INFORMATION/FREE_SPACE/LETHAL_OBSTACLE
  # False: full spectrum of intermediate values is possible
  trinary_costmap:     True

inflation_layer:
   enabled:             True
   cost_scaling_factor: 2.58   # exponential rate at which the obstacle cost drops off (default: 10)
   inflation_radius:    2.5   # max. distance from an obstacle at which costs are incurred for planning paths.

