local_costmap:
  #We'll publish the voxel grid used by this costmap - how about no

  #Set the global and robot frames for the costmap
  global_frame:     /odom
  robot_base_frame: base_link

  #Set the update and publish frequency of the costmap
  update_frequency:  10.0
  publish_frequency: 10.0
    
  #We'll configure this costmap to be a rolling window... meaning it is always
  #centered at the robot
  static_map:     False
  rolling_window: True
  width:  30.0
  height: 20.0
  resolution: 0.1
  origin_x:   0.0
  origin_y:   0.0


