obstacle_layer:
  enabled:             True
  observation_sources: velodyne_obstacles velodyne_clear laser_scan_sensor
  velodyne_obstacles:  {sensor_frame: heightmap, data_type: PointCloud2, topic: velodyne_obstacles, marking: True,  clearing: True}
  velodyne_clear:      {sensor_frame: heightmap, data_type: PointCloud2, topic: velodyne_clear,     marking: False, clearing: True}
  laser_scan_sensor:   {sensor_frame: laser,     data_type: LaserScan,   topic: scan,               marking: True,  clearing: True}
  combination_method:         1
  footprint_clearing_enabled: True # Don't mark things as obstacles if they're in footprint range
  raytrace_range:             10.0
  obstacle_range:             8.0
