TebLocalPlannerROS:

  odom_topic: /odom
  map_frame:  /map
    
  # Trajectory
  teb_autosize:                      True
  dt_ref:                            0.3
  dt_hysteresis:                     0.1
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion:  False
  max_global_plan_lookahead_dist:    3.0
  feasibility_check_no_poses:        5
    
  # Robot       
  max_vel_x:           5.0
  max_vel_x_backwards: 0.11 # shut up warning about max_vel_x_backwards<=0 (high weight_kinematics_forward_drive effectively disables backwards driving anyway)
  max_vel_y:           0.0
  max_vel_theta:       5.0 # the angular velocity is also bounded by min_turning_radius in case of a carlike robot (r = v / omega)
  acc_lim_x:           2.5
  acc_lim_theta:       2.5

  # ********************** Carlike robot parameters ********************
  min_turning_radius:       2.0    # Min turning radius of the carlike robot (compute value using a model or adjust with rqt_reconfigure manually)
  wheelbase:                1.6256 # Wheelbase of our robot (64 inches)
  cmd_angle_instead_rotvel: True   # stage simulator takes the angle instead of the rotvel as input (twist message) (also set true in ackermann mode)
  # ********************************************************************

  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type:     "polygon"
    vertices: [[1.9384, -0.6096], [1.9384, 0.6096], [-0.5, 0.6096], [-0.5, -0.6096]] # for type "polygon"
#    radius:       0.2 # for type "circular"
#    line_start:   [0.0, 0.0] # for type "line"
#    line_end:     [0.4, 0.0] # for type "line"
#    front_offset: 0.2 # for type "two_circles"
#    front_radius: 0.2 # for type "two_circles"
#    rear_offset:  0.2 # for type "two_circles"
#    rear_radius:  0.2 # for type "two_circles"

  # GoalTolerance
  xy_goal_tolerance:  0.2
  yaw_goal_tolerance: 1.0  # Allowed final orientation error in radians
  free_goal_vel:      False
    
  # Obstacles  
  min_obstacle_dist:                   0.25
  include_costmap_obstacles:           True
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected:             30
  costmap_converter_plugin:            "costmap_converter::CostmapToPolygonsDBSMCCH"
#  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSRANSAC"
#  costmap_converter_plugin: "costmap_converter::CostmapToLinesDBSMCCH"
#  costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSConcaveHull"
  costmap_converter_spin_thread:       True
  costmap_converter_rate:              5

  # Optimization  
  no_inner_iterations:              5
  no_outer_iterations:              4
  optimization_activate:            True
  optimization_verbose:             False
  penalty_epsilon:                  0.1
  weight_max_vel_x:                 2
  weight_max_vel_y:                 0
  weight_max_vel_theta:             1
  weight_acc_lim_x:                 1
  weight_acc_lim_y:                 0
  weight_acc_lim_theta:             1
  weight_kinematics_nh:             1000
  weight_kinematics_forward_drive:  1000
  weight_kinematics_turning_radius: 1
  weight_optimaltime:               1
  weight_obstacle:                  50
  weight_dynamic_obstacle:          10 # not in use yet
#  weight_viapoint:                  1.0
  selection_alternative_time_cost:  False 

  # Homotopy Class Planner
  enable_homotopy_class_planning: True # Requires more CPU resources
  enable_multithreading:          True
  simple_exploration:             False
  max_number_classes:             4
  selection_cost_hysteresis:      1.0
  selection_obst_cost_scale:      100.0
  selection_prefer_initial_plan:  0.95
  selection_viapoint_cost_scale:  1.0
  roadmap_graph_no_samples:       15
  roadmap_graph_area_width:       5
  h_signature_prescaler:          0.5
  h_signature_threshold:          0.1
  obstacle_keypoint_offset:       0.1
  obstacle_heading_threshold:     0.45
  visualize_hc_graph:             False
